---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.grafana.label.app }}
spec:
  ports:
    - port: {{ .Values.grafana.container.port }}
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: {{ .Values.grafana.label.app }}
  sessionAffinity: None
  type: LoadBalancer